name: build-and-test
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with: { dotnet-version: '8.x' }
    - run: dotnet restore
    - run: dotnet build -c Release --no-restore
    - run: dotnet test FreelanceTracker.Tests -c Release --no-build --logger trx

